apiVersion: k8s.nginx.org/v1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
  namespace: nginx-ingress
spec:
  type: deployment
  image:
    repository: nginx/nginx-ingress
    tag: 1.9.1
    pullPolicy: Always
  serviceType: LoadBalancer
  nginxPlus: False

